config/routes.rb
Rails.application.routes.draw do
  resources :qualidades
  resources :depoimentos
  resources :animes
  root "animes#index"
end

app/models/anime.rb
class Anime < ApplicationRecord
  belongs_to:depoimento
  belongs_to:qualidade
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/depoimento.rb
class Depoimento < ApplicationRecord
end

app/models/qualidade.rb
class Qualidade < ApplicationRecord
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: %i[ show edit update destroy ]

  # GET /animes or /animes.json
  def index
    @animes = Anime.all
  end

  # GET /animes/1 or /animes/1.json
  def show
  end

  # GET /animes/new
  def new
    @anime = Anime.new
  end

  # GET /animes/1/edit
  def edit
  end

  # POST /animes or /animes.json
  def create
    @anime = Anime.new(anime_params)

    respond_to do |format|
      if @anime.save
        format.html { redirect_to anime_url(@anime), notice: "Anime adicionado." }
        format.json { render :show, status: :created, location: @anime }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animes/1 or /animes/1.json
  def update
    respond_to do |format|
      if @anime.update(anime_params)
        format.html { redirect_to anime_url(@anime), notice: "Anime atualizado" }
        format.json { render :show, status: :ok, location: @anime }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @anime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animes/1 or /animes/1.json
  def destroy
    @anime.destroy

    respond_to do |format|
      format.html { redirect_to animes_url, notice: "Anime apagado" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anime
      @anime = Anime.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def anime_params
      params.require(:anime).permit(:nome, :ano, :episodios, :categoria, :depoimento_id, :qualidade_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/depoimentos_controller.rb
class DepoimentosController < ApplicationController
  before_action :set_depoimento, only: %i[ show edit update destroy ]

  # GET /depoimentos or /depoimentos.json
  def index
    @depoimentos = Depoimento.all
  end

  # GET /depoimentos/1 or /depoimentos/1.json
  def show
  end

  # GET /depoimentos/new
  def new
    @depoimento = Depoimento.new
  end

  # GET /depoimentos/1/edit
  def edit
  end

  # POST /depoimentos or /depoimentos.json
  def create
    @depoimento = Depoimento.new(depoimento_params)

    respond_to do |format|
      if @depoimento.save
        format.html { redirect_to depoimento_url(@depoimento), notice: "Depoimento was successfully created." }
        format.json { render :show, status: :created, location: @depoimento }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @depoimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /depoimentos/1 or /depoimentos/1.json
  def update
    respond_to do |format|
      if @depoimento.update(depoimento_params)
        format.html { redirect_to depoimento_url(@depoimento), notice: "Depoimento was successfully updated." }
        format.json { render :show, status: :ok, location: @depoimento }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @depoimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /depoimentos/1 or /depoimentos/1.json
  def destroy
    @depoimento.destroy

    respond_to do |format|
      format.html { redirect_to depoimentos_url, notice: "Depoimento was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_depoimento
      @depoimento = Depoimento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def depoimento_params
      params.require(:depoimento).permit(:descricao)
    end
end

app/controllers/qualidades_controller.rb
class QualidadesController < ApplicationController
  before_action :set_qualidade, only: %i[ show edit update destroy ]

  # GET /qualidades or /qualidades.json
  def index
    @qualidades = Qualidade.all
  end

  # GET /qualidades/1 or /qualidades/1.json
  def show
  end

  # GET /qualidades/new
  def new
    @qualidade = Qualidade.new
  end

  # GET /qualidades/1/edit
  def edit
  end

  # POST /qualidades or /qualidades.json
  def create
    @qualidade = Qualidade.new(qualidade_params)

    respond_to do |format|
      if @qualidade.save
        format.html { redirect_to qualidade_url(@qualidade), notice: "Qualidade was successfully created." }
        format.json { render :show, status: :created, location: @qualidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @qualidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qualidades/1 or /qualidades/1.json
  def update
    respond_to do |format|
      if @qualidade.update(qualidade_params)
        format.html { redirect_to qualidade_url(@qualidade), notice: "Qualidade was successfully updated." }
        format.json { render :show, status: :ok, location: @qualidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @qualidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualidades/1 or /qualidades/1.json
  def destroy
    @qualidade.destroy

    respond_to do |format|
      format.html { redirect_to qualidades_url, notice: "Qualidade was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qualidade
      @qualidade = Qualidade.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def qualidade_params
      params.require(:qualidade).permit(:descricao)
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depoimentos_helper.rb
module DepoimentosHelper
end

app/helpers/qualidades_helper.rb
module QualidadesHelper
end

app/views/animes/_anime.html.erb
<div id="<%= dom_id anime %>">
  <p>
    <strong>Nome:</strong>
    <%= anime.nome %>
  </p>

  <p>
    <strong>Ano:</strong>
    <%= anime.ano %>
  </p>

  <p>
    <strong>Episodios:</strong>
    <%= anime.episodios %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= anime.categoria %>
  </p>

   <p>
    <strong>Depoimento:</strong>
    <%= anime.depoimento.descricao %>
  </p>

  <p>
    <strong>Qualidade:</strong>
    <%= anime.qualidade.descricao %>
  </p>
  
</div>

app/views/animes/_form.html.erb
<%= form_with(model: anime) do |form| %>
  <% if anime.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(anime.errors.count, "error") %> prohibited this anime from being saved:</h2>

      <ul>
        <% anime.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= form.label :depoimento %>
    <%= collection_select(:anime, :depoimento_id,Depoimento.all ,:id, :descricao)%>
  </div>

<div class="field">
    <%= form.label :qualidade %>
    <%= collection_select(:anime, :qualidade_id,Qualidade.all ,:id, :descricao)%>
  </div>
    
  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano, style: "display: block" %>
    <%= form.date_field :ano %>
  </div>

  <div>
    <%= form.label :episodios, style: "display: block" %>
    <%= form.number_field :episodios %>
  </div>

  <div>
    <%= form.label :categoria, style: "display: block" %>
    <%= form.text_area :categoria %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animes/edit.html.erb
<h1>Editar anime</h1>

<%= render "form", anime: @anime %>

<br>

<div>
  <%= link_to "Mostrar anime", @anime %> |
  <%= link_to "Voltar para animes", animes_path %>
</div>

app/views/animes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Animes</h1>

<div id="animes">
  <% @animes.each do |anime| %>
    <%= render anime %>
    <p>
      <%= link_to "Mostrar anime", anime %>
    </p>
  <% end %>
</div>

<%= link_to "Novo anime", new_anime_path %>

app/views/animes/new.html.erb
<h1>Novo anime</h1>

<%= render "form", anime: @anime %>

<br>

<div>
  <%= link_to "Voltar para animes", animes_path %>
</div>

app/views/animes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @anime %>

<div>
  <%= link_to "Editar anime", edit_anime_path(@anime) %> |
  <%= link_to "Voltar para animes", animes_path %>

  <%= button_to "Apagar anime", @anime, method: :delete %>
</div>

app/views/depoimentos/_depoimento.html.erb
<div id="<%= dom_id depoimento %>">
  <p>
    <strong>Descricao:</strong>
    <%= depoimento.descricao %>
  </p>

</div>

app/views/depoimentos/_form.html.erb
<%= form_with(model: depoimento) do |form| %>
  <% if depoimento.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(depoimento.errors.count, "error") %> prohibited this depoimento from being saved:</h2>

      <ul>
        <% depoimento.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/depoimentos/edit.html.erb
<h1>Editing depoimento</h1>

<%= render "form", depoimento: @depoimento %>

<br>

<div>
  <%= link_to "Show this depoimento", @depoimento %> |
  <%= link_to "Back to depoimentos", depoimentos_path %>
</div>

app/views/depoimentos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Depoimentos</h1>

<div id="depoimentos">
  <% @depoimentos.each do |depoimento| %>
    <%= render depoimento %>
    <p>
      <%= link_to "Show this depoimento", depoimento %>
    </p>
  <% end %>
</div>

<%= link_to "New depoimento", new_depoimento_path %>

app/views/depoimentos/new.html.erb
<h1>New depoimento</h1>

<%= render "form", depoimento: @depoimento %>

<br>

<div>
  <%= link_to "Back to depoimentos", depoimentos_path %>
</div>

app/views/depoimentos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @depoimento %>

<div>
  <%= link_to "Edit this depoimento", edit_depoimento_path(@depoimento) %> |
  <%= link_to "Back to depoimentos", depoimentos_path %>

  <%= button_to "Destroy this depoimento", @depoimento, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

         <style>
     @import url('https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@1,200&display=swap');
body {
  background-color: #636485;
  font-family: 'Josefin Sans', sans-serif;
  margin: 0;
  padding: 0;
}

h1 {
  color: #4a9fdc;
  text-align:center;
  font-size: 46px;
  margin:10;
}

#animes {
  margin-top: 20px;
  color:#120907; 
}

#animes div {
  background-color:#e7d9ed;
  border-radius: 15px;
  padding: 35px;
  margin-bottom: 20px;
  text-align:justify;
  height: 350px;
  width: 350px;
}

#animes p {
  margin-bottom: 10px;
}

#animes a {
  color: #081cc9;
  text-decoration: none;
  font-size:15;
}

#animes a:hover {
  text-decoration: underline;
}

    </style>
      
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/qualidades/_form.html.erb
<%= form_with(model: qualidade) do |form| %>
  <% if qualidade.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(qualidade.errors.count, "error") %> prohibited this qualidade from being saved:</h2>

      <ul>
        <% qualidade.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_area :descricao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/qualidades/_qualidade.html.erb
<div id="<%= dom_id qualidade %>">
  <p>
    <strong>Descricao:</strong>
    <%= qualidade.descricao %>
  </p>

</div>

app/views/qualidades/edit.html.erb
<h1>Editing qualidade</h1>

<%= render "form", qualidade: @qualidade %>

<br>

<div>
  <%= link_to "Show this qualidade", @qualidade %> |
  <%= link_to "Back to qualidades", qualidades_path %>
</div>

app/views/qualidades/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Qualidades</h1>

<div id="qualidades">
  <% @qualidades.each do |qualidade| %>
    <%= render qualidade %>
    <p>
      <%= link_to "Show this qualidade", qualidade %>
    </p>
  <% end %>
</div>

<%= link_to "New qualidade", new_qualidade_path %>

app/views/qualidades/new.html.erb
<h1>New qualidade</h1>

<%= render "form", qualidade: @qualidade %>

<br>

<div>
  <%= link_to "Back to qualidades", qualidades_path %>
</div>

app/views/qualidades/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @qualidade %>

<div>
  <%= link_to "Edit this qualidade", edit_qualidade_path(@qualidade) %> |
  <%= link_to "Back to qualidades", qualidades_path %>

  <%= button_to "Destroy this qualidade", @qualidade, method: :delete %>
</div>